- id: '1500252033618'
  alias: garage_door_opened
  trigger:
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Garage door was opened!
    service: script.notify_all
- id: '1500252439165'
  alias: garage_door_closed
  trigger:
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Garage door was closed!
    service: script.notify_all
- action:
  - data:
      message: pong
    service: notify.telegram_notify
  alias: Telegram bot that reply pong to ping
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  id: 3c964bd9ca914c068ccde70a99e865ec
- action:
  - data_template:
      message: '{%- if states.sensor.garage_sensor_access_control_2_9.state == ''23''
        %} closed {%- elif states.sensor.garage_sensor_access_control_2_9.state ==
        ''22'' %} open {%- else %} {{states.sensor.garage_sensor_access_control_2_9.state}}
        {%- endif %}

        '
    service: notify.telegram_notify
  alias: Get garage door status
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /garage_door_status
  id: 41af0bffdd604c7ca10d8dd893dc3c2a
- id: '1500789219671'
  alias: sensor_case_removed
  trigger:
  - entity_id: sensor.garage_sensor_burglar
    from: '0'
    platform: state
    to: '3'
  action:
  - data:
      message: Garage door sensor case was removed!
    service: script.notify_all
- id: '1500789719339'
  alias: garage_door_sensor_low_power
  trigger:
  - entity_id: sensor.garage_sensor_power_management
    from: '0'
    platform: state
    to: '11'
  action:
  - data:
      message: Low power for garage door sensor
    service: script.notify_all
- action:
  - service: homeassistant.restart
  alias: Restart home assistant
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /restart_hass
  id: 8fb931af9bae4a8a92b03fd9e114d10f
- alias: Auto Renew SSL Cert
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
  id: 08088ce9659a4c02841534f5220d46c7
- alias: SSL expiry notification
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.telegram_notify
    data:
      message: Warning - SSL certificate expires in 21 days and has not been automatically
        renewed
  id: 70f56b5e870246a89a8105ff5c810bb2
- id: '1507784093722'
  alias: high_temperature
  trigger:
  - above: '100'
    below: '1000'
    entity_id: sensor.fibaro_door_sensor_temperature
    platform: numeric_state
  action:
  - data:
      message: High temperature!
    service: script.notify_all
- id: '1517797065431'
  alias: normal_temperature
  trigger:
  - above: '0'
    below: '100'
    entity_id: sensor.fibaro_door_sensor_temperature
    platform: numeric_state
  action:
  - data:
      message: Normal  temperature
    service: script.notify_all
- action:
  - service: script.notify_all
    data:
      message: Fire alert!!!!
  alias: fire_alert
  trigger:
    platform: template
    value_template: '{% if states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state
      == ''1'' %}true{% endif %}'
  id: 64bb30a2d16f45978c161c12b75e14dd
- action:
  - service: script.notify_all
    data:
      message: CO alert!!!!
  alias: co_alert
  trigger:
    platform: template
    value_template: '{% if states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state
      == ''2'' %}true{% endif %}'
  id: 7bada79962d14c53ae5195f3055d8b78
- action:
  - service: script.notify_all
    data:
      message: Alarm testing
  alias: alarm_testing
  trigger:
    platform: template
    value_template: '{% if states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state
      == ''12'' %}true{% endif %}'
  id: efc3a86d9485418d9d99dbdba0e525af
- id: '1520122187139'
  alias: fire_alram_low_battery
  trigger:
  - below: '30'
    entity_id: zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector
    platform: numeric_state
    value_template: states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector_10.attributes.battery_level
  action:
  - data:
      message: Low battery for fire alarm
    service: script.notify_all
- id: '1536450552696'
  alias: kirill_left_home
  trigger:
  - entity_id: device_tracker.kirill_siphone
    from: '''home'''
    platform: state
    to: '''not_home'''
  action:
  - alias: ''
    data:
      message: Kirill has left home
    service: script.notify_lena
- id: '1548020412003'
  alias: Balcony door was opened
  trigger:
  - entity_id: ' binary_sensor.neo_coolcam_door_window_detector_sensor'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      message: Balcony door was opened!
    service: script.notify_all
- id: '1548020473891'
  alias: Balcony door was closed
  trigger:
  - entity_id: ' binary_sensor.neo_coolcam_door_window_detector_sensor'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Balcony door was closed
    service: script.notify_all
