- action:
  - service: script.notify_all
    data:
      message: 'Garage door was opened!'
  alias: garage_door_opened
  id: '1500252033618'
  trigger:
  - entity_id: sensor.garage_sensor_access_control_2_9
    from: '23'
    platform: state
    to: '22'
- action:
  - service: script.notify_all
    data:
      message: 'Garage door was closed!'
  alias: garage_door_closed
  id: '1500252439165'
  trigger:
  - entity_id: sensor.garage_sensor_access_control_2_9
    from: '22'
    platform: state
    to: '23'
- action:
  - data:
      message: pong
    service: notify.telegram_notify
  alias: Telegram bot that reply pong to ping
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
- action:
  - data_template:
      message: '{%- if states.sensor.garage_sensor_access_control_2_9.state == ''23''
        %} closed {%- elif states.sensor.garage_sensor_access_control_2_9.state ==
        ''22'' %} open {%- else %} {{states.sensor.garage_sensor_access_control_2_9.state}}
        {%- endif %}

        '
    service: notify.telegram_notify
  alias: Get garage door status
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /garage_door_status
- action:
  - service: script.notify_all
    data:
      message: 'Garage door sensor case was removed!'  
  alias: sensor_case_removed
  id: '1500789219671'
  trigger:
  - entity_id: sensor.garage_sensor_burglar_2_10
    from: '0'
    platform: state
    to: '3'
- action:
  - service: script.notify_all
    data:
      message: 'Low power for garage door sensor'  
  alias: garage_door_sensor_low_power
  id: '1500789719339'
  trigger:
  - entity_id: sensor.garage_sensor_power_management_2_11
    from: '0'
    platform: state
    to: '11'
- action:
  - service: homeassistant.restart
  alias: Restart home assistant
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /restart_hass
- alias: Auto Renew SSL Cert
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
- alias: SSL expiry notification
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.telegram_notify
    data:
      message: Warning - SSL certificate expires in 21 days and has not been automatically
        renewed
- action:
  - service: script.notify_all
    data:
      message: 'High temperature!'  
  alias: high_temperature
  id: '1507784093722'
  trigger:
  - above: '86'
    below: '1000'
    entity_id: sensor.fibaro_door_sensor_temperature_8_1
    platform: numeric_state
- action:
  - service: script.notify_all
    data:
      message: 'Normal  temperature'  
  alias: normal_temperature
  id: '1517797065431'
  trigger:
  - above: '0'
    below: '86'
    entity_id: sensor.fibaro_door_sensor_temperature_8_1
    platform: numeric_state
