homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

  auth_providers:
   - type: legacy_api_password
   - type: homeassistant


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
# Uncomment this to add a password (recommended!)
  api_password: !secret api_password
# Uncomment this if you are using SSL or running in Docker etc
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
# sensor:
#   platform: yr
  
sensor:
  - platform: template
    sensors:
      garage_door_state:
        friendly_name: 'Garage door'
        value_template: >-
          {%- if states.sensor.garage_sensor_access_control.state == '23' %}
            closed
          {%- elif states.sensor.garage_sensor_access_control.state == '22' %}
            open
          {%- else %}
            {{states.sensor.garage_sensor_access_control.state}}
          {%- endif %}

  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_expiry_command

  - platform: template
    sensors:
      status_smoke_co_alarm:
        value_template: >-
          {%- if states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_level.state ==  "0" %}
              Idle
          {%- elif states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state == "1" %}
              Fire Detected
          {%- elif states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state == "2" %}
              Carbon Monoxide Detected
          {%- elif states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state == "12"  %}
              Alarm Testing
          {%- elif states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state ==  "13" %}
              Idle
          {% else %}
              {{states.sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type.state}}
          {%- endif %}
        friendly_name: 'Smoke/CO Alarm'

  - platform: template
    sensors:
      battery_level_smoke_co_alarm:
        value_template: '{{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector.attributes.battery_level}}'
        friendly_name: 'Smoke/CO Alarm Battery'
        unit_of_measurement: '%'

  - platform: template
    sensors:
      battery_level_garage_door:
        value_template: '{{states.zwave.garage_sensor.attributes.battery_level}}'
        friendly_name: 'Garage Door Sensor Battery'
        unit_of_measurement: '%'

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

ecobee:
  api_key: !secret ecobee_api_key
  
telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret telegram_bot_allowed_chat_id_lena
    - !secret telegram_bot_allowed_chat_id_kirill

notify:
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_bot_allowed_chat_id_lena

device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: lena

zwave:
  usb_path: /dev/ttyACM0 

shell_command: 
  renew_ssl: /home/homeassistant/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

ios:

script:
  notify_all:
    sequence:
      - service: telegram_bot.send_message
        data_template:
          message: "{{ message }}"
          target:
          - !secret telegram_bot_allowed_chat_id_lena
      - service: persistent_notification.create
        data_template:
          message: "{{ message }}"

  notify_lena:
    sequence:
      - service: telegram_bot.send_message
        data_template:
          message: "{{ message }}"
          target:
          - !secret telegram_bot_allowed_chat_id_lena

august:
  login_method: email
  username: "elvslv@gmail.com"
  password: !secret august_password

logger:
  default: info
  logs:
    homeassistant.components.august: info

recorder:

variable:
  front_door_open_triggered:
    value: False
  
