homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
# sensor:
#   platform: yr
  
sensor:
  - platform: template
    sensors:
      garage_door_state:
        friendly_name: 'Garage door'
        value_template: >-
          {%- if states.sensor.garage_sensor_access_control_2_9.state == '23' %}
            closed
          {%- elif states.sensor.garage_sensor_access_control_2_9.state == '22' %}
            open
          {%- else %}
            {{states.sensor.garage_sensor_access_control_2_9.state}}
          {%- endif %}

  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_expiry_command

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml

ecobee:
  api_key: !secret ecobee_api_key
  
telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret telegram_bot_allowed_chat_id_lena

notify:
  - name: telegram_notify
    platform: telegram
    chat_id: !secret telegram_bot_allowed_chat_id_lena

device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: lena

zwave:
  usb_path: /dev/ttyACM0 

shell_command: 
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01
